// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBofyRdsOeWfKe-HzwjSsokLqj085fG1Ww',
    appId: '1:561685747014:web:3313d1609e04c5ba910147',
    messagingSenderId: '561685747014',
    projectId: 'moshow-ca101',
    authDomain: 'moshow-ca101.firebaseapp.com',
    storageBucket: 'moshow-ca101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmpQIsVZgLmw68c1OZz6BcK1nrwxrtUYI',
    appId: '1:561685747014:android:fde70378e927a34c910147',
    messagingSenderId: '561685747014',
    projectId: 'moshow-ca101',
    storageBucket: 'moshow-ca101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXQuH8C1BArtE8ip9pEQH_pMw4ADQ7PTY',
    appId: '1:561685747014:ios:383fe3606981c2a6910147',
    messagingSenderId: '561685747014',
    projectId: 'moshow-ca101',
    storageBucket: 'moshow-ca101.firebasestorage.app',
    iosBundleId: 'com.deco.moshow',
  );
}
